name: Bundle Deployment for taxi-fare Staging
'on':
  push:
    branches:
    - main
  workflow_dispatch: null
defaults:
  run:
    working-directory: ./taxi_fare
jobs:
  staging:
    concurrency: taxi-fare-staging-bundle-job
    runs-on: ubuntu-latest
    environment: databricks_staging
    env:
      DATABRICKS_TOKEN: ${{secrets.WORKSPACE_TOKEN}}
      DATABRICKS_HOST: ${{secrets.WORKSPACE_HOST}}
    steps:
    - uses: actions/checkout@v3
    - uses: databricks/setup-cli@main
    - name: Validate Bundle For Staging
      id: validate
      run: 'databricks bundle validate -t stg

        '
    - name: Deploy Bundle to Staging
      id: deploy
      run: 'databricks bundle deploy -t stg

        '
