name: Bundle validation for taxi-fare
'on':
  workflow_dispatch: null
  pull_request_target: null
defaults:
  run:
    working-directory: ./taxi_fare/
jobs:
  staging:
    concurrency: taxi-fare-staging-bundle-job
    permissions: write-all
    runs-on: ubuntu-latest
    environment: databricks_staging
    steps:
    - uses: actions/checkout@v3
      with:
        ref: ${{ github.event.pull_request.head.sha || github.sha }}
    - uses: databricks/setup-cli@main
    - name: Validate Bundle For Staging
      id: validate
      env:
        DATABRICKS_TOKEN: ${{secrets.WORKSPACE_TOKEN}}
        DATABRICKS_HOST: ${{secrets.WORKSPACE_HOST}}
      run: 'databricks bundle validate -t stg > ../validate_output.txt

        '
    - name: Create Comment with Bundle Configuration
      uses: actions/github-script@v6
      id: comment
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        script: "const fs = require('fs');\nconst fileContents = fs.readFileSync('validate_output.txt',\
          \ 'utf8');\nconst output = `#### Bundle Staging Config Validated \U0001F58C\
          \n<details><summary>Staging Validation Output</summary>\n\n\\`\\`\\`\\n\n\
          ${fileContents}\n\\`\\`\\`\n\n</details>`\n\ngithub.rest.issues.createComment({\n\
          \  issue_number: context.issue.number,\n  owner: context.repo.owner,\n \
          \ repo: context.repo.repo,\n  body: output\n})\n"
  prod:
    concurrency: taxi-fare-prod-bundle-job
    permissions: write-all
    runs-on: ubuntu-latest
    environment: databricks_prod
    steps:
    - uses: actions/checkout@v3
      with:
        ref: ${{ github.event.pull_request.head.sha || github.sha }}
    - uses: databricks/setup-cli@main
    - name: Validate Bundle For Prod
      id: validate
      env:
        DATABRICKS_TOKEN: ${{secrets.WORKSPACE_TOKEN}}
        DATABRICKS_HOST: ${{secrets.WORKSPACE_HOST}}
      run: 'databricks bundle validate -t prd > ../validate_output.txt

        '
    - name: Create Comment with Bundle Configuration
      uses: actions/github-script@v6
      id: comment
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        script: "const fs = require('fs');\nconst fileContents = fs.readFileSync('validate_output.txt',\
          \ 'utf8');\nconst output = `#### Bundle Prod Config Validated \U0001F58C\
          \n<details><summary>Prod Validation Output</summary>\n\n\\`\\`\\`\\n\n${fileContents}\n\
          \\`\\`\\`\n\n</details>`\n\ngithub.rest.issues.createComment({\n  issue_number:\
          \ context.issue.number,\n  owner: context.repo.owner,\n  repo: context.repo.repo,\n\
          \  body: output\n})\n"
