name: Bundle Deployment for taxi-fare Prod
'on':
  release:
    types:
    - published
  push:
    branches:
    - releases/**
    - release
  workflow_dispatch: null
defaults:
  run:
    working-directory: ./taxi_fare
jobs:
  prod:
    concurrency: taxi-fare-prod-bundle-job
    runs-on: ubuntu-latest
    environment: databricks_prod
    env:
      DATABRICKS_TOKEN: ${{secrets.WORKSPACE_TOKEN}}
      DATABRICKS_HOST: ${{secrets.WORKSPACE_HOST}}
    steps:
    - uses: actions/checkout@v3
    - uses: databricks/setup-cli@main
    - name: Validate Bundle For Prod
      id: validate
      run: 'databricks bundle validate -t prd

        '
    - name: Deploy Bundle to Prod
      id: deploy
      run: 'databricks bundle deploy -t prd

        '
